apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-talos-discovery-service.fullname" . }}
  labels:
    {{- include "helm-talos-discovery-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.grpc }}
    nodePort: {{ .Values.service.nodePorts.grpc }}
    {{- end }}
  - port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePorts.http }}
    nodePort: {{ .Values.service.nodePorts.http }}
    {{- end }}
  selector:
    {{- include "helm-talos-discovery-service.selectorLabels" . | nindent 4 }}
